### ISSUE TITLE
itk.TubeTKPython has no attribute itkImageF4 - warning

### ISSUE THREAD

**Issue by aylward** [InsightSoftwareConsortium/ITKTubeTK#121]
TubeTK will almost always and on every platform generate the warning:

>  module 'itk.TubeTKPython' has no attribute 'itkImageF4'
> vectoritkImageF4 not loaded from module TubeTK because of exception:
>  module 'itk.TubeTKPython' has no attribute 'vectoritkImageF4'

This is not an error, it is a warning, and TubeTK will work fine despite this warning.

I believe that this warning indicates that the 4D vector of float image used in TubeTK is not included in the currently installed, python wrapped version of itk.  This only matters if you want to process 4D vector of float images, which is highly unlikely.   Again, TubeTK should work fine, despite this warning.

Proposed fix: (1) Confirm with ITK Python gurus what this warning means.  (2) If it means what I think it means, TubeTK should detect what types of images are supported in the python wrapped itk against which it is being built, and not provide support for 4D vector of float images, if the python wrapped itk doesn't support them.

**Comment by thewtex** [comment]
>  this warning indicates that the 4D vector of float image used in TubeTK is not included in the currently installed, python wrapped version of itk

:+1: yes

Checking with `itk-5.3.0`,

```
>>> itk.vector[itk.Image[itk.F, 3]]
<class 'itk.itkImagePython.vectoritkImageF3'>
>>> itk.Image[itk.F, 4]
<class 'itk.itkImagePython.itkImageF4'>
```

so maybe this has been addressed?

**Comment by aylward** [comment]
LGTM!   Thanks @thewtex !!!
